# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 967acecd5fab1ec397c1acd73161d00d2ef209d7d4f9d7b072b3070c8066d262bc75ffc00578a8e47bd1ea42981090e8f2ba41e06d472b0de209239c77209c97

test:
  secret_key_base: 637706c513bb7513cefbff96d77d1241454ca2e6c6c6319ea51d326a5efbe7b3bfddb148adff9cc48a5ba04dede3670d9a61e896a17f3066b7bd6e54f622559d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
